version: '3'
volumes:
  data:
networks:
  database:
  web:
services: 
  db:
    image: postgres:9.6
    # data volume
    volumes: 
      - data:/var/lib/postgresql/data
      #scripts volume
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - database
  frontend:
    image: nginx:1.13
    volumes:
      #wep page
      - ./web:/usr/share/nginx/html/
      #reverse proxy configuration
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    networks: 
      - web
    depends_on:
      - app
  app:
    image: python:3.6
    volumes:
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh
    networks: 
     - database
     - web
    depends_on: 
      - db
     
