version: '3'
volumes:
  data:
services: 
  db:
    image: postgres:9.6
    # data volume
    volumes: 
      - data:/var/lib/postgresql/data
      #scripts volume
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql