version: '3'
volumes:
  data:
services: 
  db:
    image: postgres:9.6
    # data volume
    volumes: 
      - data:/var/lib/postgresql/data
      #scripts volume
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
  frontend:
    image: nginx:1.13
    volumes:
      - ./web:/usr/share/nginx/html/
    ports:
      - 80:80
  app:
    image: python:latest
    volumes:
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh
    ports: 
      - 8080:8080
